version: '3.8'

services:
  app:
    image: demo_solid_queue
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - demo_solid_queue_app_network
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - demo_solid_queue_app_network

networks:
  demo_solid_queue_app_network:
    driver: bridge
