name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  rubocop-with-reviewdog:
    name: rubocop with reviewdog
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # v1.268.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: reviewdog/action-rubocop@fcb74ba274da10b18d038d0bcddaae3518739634 # v2.21.2
        with:
          reporter: github-pr-review # Default is github-pr-check
          fail_level: any
          only_changed: true
          skip_install: true
          use_bundler: true
