name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  rubocop-with-reviewdog:
    name: rubocop with reviewdog
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: reviewdog/action-rubocop@b6d5e953a5fc0bf3ab65254e77730ea2174d6d6d # v2.22.0
        with:
          reporter: github-pr-review # Default is github-pr-check
          fail_level: any
          only_changed: true
          skip_install: true
          use_bundler: true
